export type LedgerClass='income'|'expense'|'transfer'|'debt-principal'|'receivable-principal'|'interest-income'|'interest-expense'|'forecast'
export type LedgerEntry={id:number;date:string;description:string;debitAccount:string;creditAccount:string;amount:number;classification:LedgerClass;linkedType:string;linkedId:number;actual:boolean}
export type CategoryBudget={id:number;name:string;parent:string;subcategory:string;type:string;allocated:number;incomePercentage:number;period:string;start:string;end:string;rollover:boolean;rolloverLimit:number;includePlanned:boolean;includePending:boolean;warning:number;critical:number;actual:number;planned:number;status:string;notes:string;archived:boolean}
export type Debt={id:number;name:string;lender:string;type:string;original:number;balance:number;interestType:string;interestRate:number;fees:number;paymentAmount:number;frequency:string;start:string;nextDue:string;finalDue:string;paymentAccount:string;liabilityAccount:string;status:string;principalPaid:number;interestPaid:number;notes:string;archived:boolean}
export type Receivable={id:number;title:string;borrower:string;contact:string;type:string;original:number;additional:number;interest:number;fees:number;collectedPrincipal:number;collectedInterest:number;writeOff:number;transactionDate:string;expectedDate:string;sourceAccount:string;collectionAccount:string;status:string;notes:string;archived:boolean;businessIncome?:number;incomeFrequency?:string;collectionHistory?:Array<{id:number;date:string;principal:number;interest:number;fees:number;account:string;status:string;reference?:string;notes?:string}>}
export type PlannedPayment={id:number;name:string;type:string;amount:number;confidence:'Confirmed'|'Estimated';expectedDate:string;dueDate:string;source:string;destination:string;category:string;linkedModule:string;frequency:string;recurrenceEnd:string;autoPost:boolean;status:string;actualAmount:number;postedTransactionId?:number;notes:string;archived:boolean}
export type Installment={id:number;name:string;merchant:string;category:string;type:string;original:number;downPayment:number;interest:number;fees:number;count:number;paidCount:number;amount:number;frequency:string;start:string;nextDue:string;finalDue:string;fundingSource:string;linkedCard:string;mode:'Expense at Purchase'|'Expense by Installment';remainingPrincipal:number;remainingPayable:number;status:string;notes:string;archived:boolean}

export const clampDay=(year:number,month:number,day:number)=>new Date(year,month,Math.min(day,new Date(year,month+1,0).getDate()),12)
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
export function recurrenceDates(start:string,count:number){const d=new Date(`${start}T12:00`),day=d.getDate();return Array.from({length:count},(_,i)=>iso(clampDay(d.getFullYear(),d.getMonth()+i,day)))}
export function budgetMetrics(b:CategoryBudget,today='2026-07-20'){const actualRemaining=b.allocated-b.actual,forecastedRemaining=b.allocated-b.actual-b.planned,usage=b.allocated?b.actual/b.allocated*100:0,forecastedUsage=b.allocated?(b.actual+b.planned)/b.allocated*100:0,days=Math.max(1,Math.ceil((new Date(`${b.end}T12:00`).getTime()-new Date(`${today}T12:00`).getTime())/86400000)+1),status=forecastedUsage>100?'Forecasted over budget':usage>100?'Over budget':forecastedUsage>=90?'Near limit':forecastedUsage>=70?'Monitor':'Healthy';return{actualRemaining,forecastedRemaining,usage,forecastedUsage,days,dailySafe:Math.max(0,forecastedRemaining)/days,status}}
export function borrow(debt:Debt,amount:number,date:string){return{debt:{...debt,balance:debt.balance+amount},entries:[entry(date,`Borrowed from ${debt.lender}`,debt.paymentAccount,debt.liabilityAccount,amount,'debt-principal','Debt',debt.id)]}}
export function payDebt(debt:Debt,principal:number,interest:number,fees:number,date:string){if(principal+interest+fees<=0)throw Error('Payment must be greater than zero');const balance=Math.max(0,debt.balance-principal),status=balance===0?'Fully paid':principal<debt.paymentAmount?'Partially paid':'Active';return{debt:{...debt,balance,principalPaid:debt.principalPaid+principal,interestPaid:debt.interestPaid+interest,status},entries:[entry(date,`Debt principal · ${debt.name}`,debt.liabilityAccount,debt.paymentAccount,principal,'debt-principal','Debt',debt.id),...(interest?[entry(date,`Debt interest · ${debt.name}`,'Interest expense',debt.paymentAccount,interest,'interest-expense','Debt',debt.id)]:[]),...(fees?[entry(date,`Debt fee · ${debt.name}`,'Fee expense',debt.paymentAccount,fees,'expense','Debt',debt.id)]:[])]}}
export function lend(r:Receivable,date:string){return{receivable:r,entries:[entry(date,`Lent to ${r.borrower}`,'Receivable',r.sourceAccount,r.original,'receivable-principal','Receivable',r.id)]}}
const isBusinessReceivable=(r:Receivable)=>/business|investment/i.test(r.type)
export function collect(r:Receivable,principal:number,interest:number,fees:number,date:string,account=r.collectionAccount,reference='',notes=''){const interestOwed=isBusinessReceivable(r)?0:r.interest,collectedInterestForOutstanding=isBusinessReceivable(r)?0:r.collectedInterest,outstanding=Math.max(0,r.original+r.additional+interestOwed+r.fees-r.collectedPrincipal-collectedInterestForOutstanding-r.writeOff-principal-(isBusinessReceivable(r)?0:interest)-fees),status=outstanding===0?'Fully collected':principal+interest+fees>0?'Partially collected':r.status;return{receivable:{...r,collectionAccount:account,collectedPrincipal:r.collectedPrincipal+principal,collectedInterest:r.collectedInterest+interest,status,collectionHistory:[...(r.collectionHistory??[]),{id:Date.now(),date,principal,interest,fees,account,status:'Posted',reference,notes}]},entries:[entry(date,`Principal collection · ${r.title}`,account,'Receivable',principal,'receivable-principal','Receivable',r.id),...(interest+fees?[entry(date,`Income collection · ${r.title}`,account,'Interest income',interest+fees,'interest-income','Receivable',r.id)]:[])]}}
export const receivableOutstanding=(r:Receivable)=>{const interestOwed=isBusinessReceivable(r)?0:r.interest,collectedInterestForOutstanding=isBusinessReceivable(r)?0:r.collectedInterest;return Math.max(0,r.original+r.additional+interestOwed+r.fees-r.collectedPrincipal-collectedInterestForOutstanding-r.writeOff)}
export function completePlanned(p:PlannedPayment,actual:number,date:string){const remaining=Math.max(0,p.amount-actual),status=remaining===0?'Completed':'Partially completed',id=Date.now();return{payment:{...p,actualAmount:p.actualAmount+actual,status,postedTransactionId:id},remaining,entry:entry(date,p.name,p.destination||p.category,p.source,actual,p.type==='Income'?'income':p.type==='Receivable collection'?'receivable-principal':p.type==='Transfer'?'transfer':'expense','PlannedPayment',p.id,id)}}
export function installmentSchedule(i:Installment){const dates=recurrenceDates(i.nextDue,i.count-i.paidCount);return dates.map((date,index)=>({number:i.paidCount+index+1,dueDate:date,amount:index===dates.length-1?i.remainingPayable-i.amount*(dates.length-1):i.amount,status:index===0?'Upcoming':'Planned'}))}
export function createInstallment(input:Omit<Installment,'amount'|'remainingPrincipal'|'remainingPayable'|'finalDue'|'status'>){const financed=input.original-input.downPayment,total=financed+input.interest+input.fees,amount=total/input.count,dates=recurrenceDates(input.start,input.count);return{...input,amount,remainingPrincipal:Math.max(0,financed-(financed/input.count)*input.paidCount),remainingPayable:Math.max(0,total-amount*input.paidCount),finalDue:dates.at(-1)!,status:input.paidCount>=input.count?'Completed':'Active'} as Installment}
export function payInstallment(i:Installment,amount:number,date:string){const paid=Math.min(amount,i.remainingPayable),remaining=Math.max(0,i.remainingPayable-paid),completed=Math.min(i.count,i.paidCount+(paid>=i.amount?1:0)),schedule=recurrenceDates(i.nextDue,2);return{installment:{...i,remainingPayable:remaining,remainingPrincipal:Math.max(0,i.remainingPrincipal-paid),paidCount:completed,nextDue:schedule[1],status:remaining===0?'Completed':paid<i.amount?'Partially paid':'Active'},entry:entry(date,`Installment · ${i.name}`,i.linkedCard||'Installment liability',i.fundingSource,paid,i.mode==='Expense by Installment'?'expense':'transfer','Installment',i.id)}}
export function projectedBalance(actual:number,payments:PlannedPayment[],includeEstimated=false){return payments.filter(p=>!p.archived&&p.status!=='Completed'&&(p.confidence==='Confirmed'||includeEstimated)).reduce((n,p)=>n+(p.type==='Income'||p.type==='Receivable collection'?p.amount:-p.amount),actual)}
function entry(date:string,description:string,debitAccount:string,creditAccount:string,amount:number,classification:LedgerClass,linkedType:string,linkedId:number,id=Date.now()):LedgerEntry{return{id,date,description,debitAccount,creditAccount,amount,classification,linkedType,linkedId,actual:true}}
