import { useEffect, useState } from 'react'
import { ArrowDownToLine, ArrowUpFromLine, CalendarDays, Shield, TrendingUp, Wallet } from 'lucide-react'
import { useFirestoreState } from './hooks/useFirestoreState'
import { useWalletSnapshot } from './hooks/useWalletSnapshot'
import { CategoryIcon } from './components/CategoryIcon'
import type { CategoryBudget } from './domain/planningEngine'
import { connectBudgetsToTransactions } from './utils/budgetSpending'
import { billUsesIncludedCard, filterIncludedCardTransactions } from './utils/netBalanceFilters'

type Props = { onSelect: (page: string) => void; onNotice: (message: string) => void; rangeMonths: number }
const peso=(v:string)=>`₱${v}`
const amount=(value:string|number)=>Number(String(value).replace(/[^0-9.-]/g,''))||0
const format=(value:number)=>`${value<0?'-':''}₱${Math.abs(value).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})}`
type DashboardBill={id:number;sourceKey?:string;name:string;category:string;amount:number;dueDate:string;status:string}
type DashboardWallet={accounts:{id:number;name:string;balance:number}[];cards:{id:number;bankId?:string|null;bank?:string;customLogo?:string;name:string;last4:string;creditLimit:number;sharedLimitCardId?:number|null;openingBalance:number;active?:boolean;includeInNetBalance?:boolean}[];accountTransactions:{id:number;accountId:number;date:string;type:string;category?:string;amount:number;status?:string}[];transactions:{id:number;cardId:number;transactionDate?:string;postedDate:string;type:string;category?:string;amount:number;status:string}[];payments:{id:number;cardId:number;amount:number;status:string}[]}
type DashboardPlan={id:number;name:string;amount:number;status?:string;archived?:boolean}
type DashboardPlanningItem={id:number;type:'Income'|'Expense';name:string;category:string;amount:number;date:string;status?:string;archived?:boolean}
type DashboardUpcomingRow={id:string;sortDate:string;date:string;name:string;category:string;amount:string;rawAmount:number;categoryTone:string;label:string;tone:string}

const MONTH_LABELS=['Jan.','Feb.','Mar.','Apr.','May','Jun.','Jul.','Aug.','Sep.','Oct.','Nov.','Dec.']
function rangeLabel(months:number){if(months===1)return'This month';if(months===3)return'Last 3 months';if(months===6)return'Last 6 months';if(months===7)return'January–July';if(months===12)return'Last 12 months';return`Last ${months} months`}
function parseLocalDate(value:string){const [year,month,day]=value.split('-').map(Number);return year&&month&&day?new Date(year,month-1,day):null}
function isWithinNextDays(value:string,days:number){const due=parseLocalDate(value);if(!due)return false;const today=new Date();today.setHours(0,0,0,0);const end=new Date(today);end.setDate(end.getDate()+days);return due>=today&&due<=end}
function formatUpcomingDate(value:string){const date=parseLocalDate(value);return date?`${MONTH_LABELS[date.getMonth()]} ${date.getDate()} (${date.toLocaleDateString('en-US',{weekday:'short'})})`:value}
function getDaysLeft(value:string){const due=parseLocalDate(value);if(!due)return{label:'—',tone:''};const today=new Date();today.setHours(0,0,0,0);const days=Math.round((due.getTime()-today.getTime())/86_400_000);if(days<0)return{label:`${Math.abs(days)}d overdue`,tone:'overdue'};if(days===0)return{label:'Today',tone:'due'};if(days===1)return{label:'1 day',tone:'due'};return{label:`${days} days`,tone:''}}

export default function DashboardOverview({onSelect,onNotice,rangeMonths}:Props){
 const [compactDashboard,setCompactDashboard]=useState(()=>window.matchMedia('(max-width:600px)').matches)
 const [bills]=useFirestoreState<DashboardBill[]>('bills',[]),[planning]=useFirestoreState<DashboardPlanningItem[]>('planning',[]),[savedBudgets]=useFirestoreState<CategoryBudget[]>('budgets',[]),[goals]=useFirestoreState<string[][]>('savingsGoals',[]),[debts]=useFirestoreState<DashboardPlan[]>('debts',[]),[receivables]=useFirestoreState<DashboardPlan[]>('receivables',[]),[installments]=useFirestoreState<DashboardPlan[]>('installments',[]),[wallet]=useWalletSnapshot<DashboardWallet>({accounts:[],cards:[],accountTransactions:[],transactions:[],payments:[]})
 useEffect(()=>{const query=window.matchMedia('(max-width:600px)'),sync=()=>setCompactDashboard(query.matches);sync();query.addEventListener('change',sync);return()=>query.removeEventListener('change',sync)},[])
 const includedCardTransactions=filterIncludedCardTransactions(wallet.transactions,wallet.cards),visibleBills=bills.filter(bill=>billUsesIncludedCard(bill,wallet.cards))
 const budgets=connectBudgetsToTransactions(savedBudgets,{...wallet,transactions:includedCardTransactions,cards:wallet.cards}),subcategoryBudgets=budgets.filter(budget=>budget.subcategory&&!budget.archived)
 const billRows:DashboardUpcomingRow[]=visibleBills.filter(bill=>!['Paid','Skipped'].includes(bill.status)).map(bill=>({id:`bill-${bill.id}`,sortDate:bill.dueDate,date:formatUpcomingDate(bill.dueDate),name:bill.name.replace(/\s+statement$/i,''),category:bill.category,amount:format(bill.amount),rawAmount:bill.amount,categoryTone:bill.status.toLowerCase().includes('overdue')?'amber':'green',...getDaysLeft(bill.dueDate)}))
 const planningRows:DashboardUpcomingRow[]=planning.filter(item=>!item.archived).map(item=>({id:`plan-${item.id}`,sortDate:item.date,date:formatUpcomingDate(item.date),name:item.name,category:item.type==='Income'?'Plan income':'Plan expense',amount:`${item.type==='Income'?'+':'−'}${format(item.amount)}`,rawAmount:item.type==='Income'?0:item.amount,categoryTone:item.type==='Income'?'blue':'cyan',...getDaysLeft(item.date)}))
 const upcoming=[...billRows,...planningRows].sort((a,b)=>a.sortDate.localeCompare(b.sortDate)).slice(0,5)
 const available=wallet.accounts.reduce((sum,account)=>sum+account.balance,0),safeRange=Math.max(1,Math.min(12,rangeMonths||7)),selectedRangeLabel=rangeLabel(safeRange),rangeEnd=new Date(),monthBuckets=Array.from({length:safeRange},(_,index)=>{const date=new Date(rangeEnd.getFullYear(),rangeEnd.getMonth()-(safeRange-1-index),1),key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;return{key,label:date.toLocaleDateString('en-US',{month:'long'})}}),monthlyIncome=monthBuckets.map(({key})=>wallet.accountTransactions.filter(transaction=>transaction.date.startsWith(key)&&transaction.type==='Income').reduce((sum,transaction)=>sum+transaction.amount,0)),monthlyExpenses=monthBuckets.map(({key})=>wallet.accountTransactions.filter(transaction=>transaction.date.startsWith(key)&&transaction.type==='Expense').reduce((sum,transaction)=>sum+transaction.amount,0)+includedCardTransactions.filter(transaction=>transaction.postedDate.startsWith(key)&&transaction.status==='posted'&&['purchase','installment','fee','interest'].includes(transaction.type)).reduce((sum,transaction)=>sum+transaction.amount,0)),rangeIncomeTotal=monthlyIncome.reduce((sum,value)=>sum+value,0),rangeExpenseTotal=monthlyExpenses.reduce((sum,value)=>sum+value,0),rangeNetCashFlow=rangeIncomeTotal-rangeExpenseTotal,plannedExpenseTotal=planning.filter(item=>item.type==='Expense'&&!item.archived).reduce((sum,item)=>sum+item.amount,0),dueNextSevenDaysTotal=visibleBills.filter(bill=>!['Paid','Skipped'].includes(bill.status)&&isWithinNextDays(bill.dueDate,7)).reduce((sum,bill)=>sum+bill.amount,0),safeToSpend=available-dueNextSevenDaysTotal-plannedExpenseTotal,upcomingTotal=upcoming.reduce((sum,row)=>sum+row.rawAmount,0),budgetRowsForTotals=(subcategoryBudgets.length?subcategoryBudgets:budgets.filter(budget=>!budget.archived)),budgetSpent=budgetRowsForTotals.reduce((sum,budget)=>sum+budget.actual,0),budgetTotal=budgetRowsForTotals.reduce((sum,budget)=>sum+budget.allocated,0)
 const budgetRemaining=budgetTotal-budgetSpent,budgetChartRows=budgetRowsForTotals.slice(0,7)
 return <div className="format-dashboard">
  <section className="fd-kpis">
   <Kpi icon={Wallet} label="Available balance" value={format(available)} note={`${wallet.accounts.length} accounts`} tone="green"/>
   <Kpi icon={Shield} label="Safe to spend" value={format(safeToSpend)} note={`Balance − 7-day bills − planned expenses`} tone="lime"/>
   <Kpi icon={ArrowDownToLine} label={`Income: ${selectedRangeLabel}`} value={format(rangeIncomeTotal)} note={`${monthBuckets.length} month range`} tone="blue"/>
   <Kpi icon={ArrowUpFromLine} label={`Expenses: ${selectedRangeLabel}`} value={format(rangeExpenseTotal)} note={`${monthBuckets.length} month range`} tone="red"/>
   <Kpi icon={TrendingUp} label="Net cash flow" value={format(rangeNetCashFlow)} note={rangeNetCashFlow>=0?'Income exceeded expenses':'Expenses exceeded income'} tone={rangeNetCashFlow>=0?'green':'red'}/>
  </section>
  <section className="fd-grid">
   <Panel className="fd-monthly-budget" title="Budget Performance: Current month" action="View budget" onAction={()=>onSelect('Budget')}>
    <div className="fd-legend"><span><i className="budget"/>Budget</span><span><i className="expense"/>Actual</span></div>
    <BudgetChart labels={budgetChartRows.map(budget=>budget.subcategory||budget.name)} planned={budgetChartRows.map(budget=>budget.allocated)} actual={budgetChartRows.map(budget=>budget.actual)}/>
    <div className="fd-flow-total budget-chart-total"><span>Total budget<b>{format(budgetTotal)}</b></span><span>Actual spent<b>{format(budgetSpent)}</b></span><span>Remaining<b>{format(budgetRemaining)}</b></span></div>
   </Panel>
   <Panel className="fd-flow" title={`Cash Flow: ${selectedRangeLabel}`} action="View forecast" onAction={()=>onSelect('Forecast')}>
    <div className="fd-legend"><span><i className="income"/>Income</span><span><i className="expense"/>Expenses</span><span><i className="net"/>Net</span></div><FlowChart labels={monthBuckets.map(bucket=>bucket.label)} income={monthlyIncome} expenses={monthlyExpenses}/>
    <div className="fd-flow-total"><span>Total income<b>{format(rangeIncomeTotal)}</b></span><span>Total expenses<b>{format(rangeExpenseTotal)}</b></span><span>Net cash flow<b>{format(rangeIncomeTotal-rangeExpenseTotal)}</b></span></div>
   </Panel>
   <Panel className="fd-upcoming" title="Upcoming this week" icon={<CalendarDays/>} action="View all" onAction={()=>onSelect('Calendar')}>
    <div className="fd-table-head"><span>Date</span><span>Payee / Description</span><span>Category</span><span>Days Left</span><span>Amount</span></div>
    {upcoming.map(r=><button key={r.id} onClick={()=>onNotice(`${r.name} selected`)}><span>{r.date}</span><b>{r.name}</b><em className={r.categoryTone}><CategoryIcon value={r.category}/>{r.category}</em><small className={`days-left ${r.tone}`}>{r.label}</small><strong>{r.amount}</strong></button>)}
    {!upcoming.length&&<p className="empty-card">No upcoming payments. Add a bill to get started.</p>}<div className="fd-total"><b>Total</b><strong>{format(upcomingTotal)}</strong></div>
   </Panel>
   <Panel className="fd-budgets" title="Category budgets: Current month" action="This month⌄" onAction={()=>onSelect('Budget')}>
    <div className="budget-head"><span>Category</span><span>Spent</span><span>Budget</span><span>Progress</span></div>
    {subcategoryBudgets.slice(0,5).map(budget=><div className="budget-row" key={budget.id}><span><CategoryIcon value={`${budget.name} / ${budget.subcategory}`} label/></span><strong>{format(budget.actual)}</strong><strong>{format(budget.allocated)}</strong><em>{budget.allocated?Math.round(budget.actual/budget.allocated*100):0}%</em></div>)}{!subcategoryBudgets.length&&<p className="empty-card">No subcategory budgets created.</p>}<div className="budget-total"><b>Total</b><strong>{format(subcategoryBudgets.reduce((sum,budget)=>sum+budget.actual,0))}</strong><strong>{format(subcategoryBudgets.reduce((sum,budget)=>sum+budget.allocated,0))}</strong><em>{subcategoryBudgets.reduce((sum,budget)=>sum+budget.allocated,0)?Math.round(subcategoryBudgets.reduce((sum,budget)=>sum+budget.actual,0)/subcategoryBudgets.reduce((sum,budget)=>sum+budget.allocated,0)*100):0}%</em></div>
   </Panel>
  </section>
  <details className="fd-more-details" open={!compactDashboard}>
   <summary>More financial details</summary>
   <section className="fd-mini">
   <Mini tone="red" icon="▥" title="Debt outstanding" value={format(debts.reduce((sum,item)=>sum+Number(item.amount||0),0))} count={String(debts.filter(item=>!item.archived).length)} labels={['Total outstanding','Active debts']} onClick={()=>onSelect('Debts')}/><Mini tone="green" icon="♙" title="Money owed to me" value={format(receivables.reduce((sum,item)=>sum+Number(item.amount||0),0))} count={String(receivables.filter(item=>!item.archived).length)} labels={['Total receivables','Active receivables']} onClick={()=>onSelect('Money owed to me')}/><Mini tone="blue" icon="▣" title="Upcoming bills" value={format(upcomingTotal)} count={String(bills.length)} labels={['Scheduled total','Bills']} onClick={()=>onSelect('Bills')}/><Mini tone="amber" icon="▤" title="Installments" value={format(installments.reduce((sum,item)=>sum+Number(item.amount||0),0))} count={String(installments.filter(item=>!item.archived).length)} labels={['Remaining total','Active plans']} onClick={()=>onSelect('Installments')}/>
   </section>
  </details>
 </div>
}

function Panel({title,icon,action,onAction,className,children}:{title:string;icon?:React.ReactNode;action?:string;onAction?:()=>void;className:string;children:React.ReactNode}){return <article className={`fd-panel ${className}`}><div className="fd-title"><h2>{icon}{title}</h2>{action&&<button onClick={onAction}>{action}</button>}</div>{children}</article>}
function Kpi({icon:Icon,label,value,note,tone}:{icon:typeof Wallet;label:string;value:string;note:string;tone:string}){return <article><i className={tone}><Icon/></i><div><small>{label} ⓘ</small><b>{value}</b><span className={tone}>{note}</span></div></article>}
function FlowChart({labels,income,expenses}:{labels:string[];income:number[];expenses:number[]}){const net=income.map((value,index)=>value-expenses[index]),maximum=Math.max(1,...income,...expenses,...net.map(Math.abs)),magnitude=10**Math.floor(Math.log10(maximum)),chartMax=Math.ceil(maximum/magnitude)*magnitude,axisLeft=54,axisRight=954,pointLeft=74,pointRight=934,top=24,bottom=226,zero=(top+bottom)/2,step=(pointRight-pointLeft)/Math.max(1,labels.length-1),barWidth=Math.min(28,Math.max(12,step*.22)),y=(value:number)=>zero-(value/chartMax)*(zero-top),moneyTick=(value:number)=>{const sign=value<0?'-':'',absolute=Math.abs(value);if(absolute>=1_000_000)return`${sign}₱${Number((absolute/1_000_000).toFixed(1))}M`;if(absolute>=1_000)return`${sign}₱${Number((absolute/1_000).toFixed(1))}K`;return`${sign}₱${Number(absolute.toFixed(2)).toLocaleString('en-PH',{maximumFractionDigits:2})}`};return <svg viewBox="0 0 980 280" role="img" aria-label="Monthly cash flow chart showing income, expenses, and net cash flow by month"><title>Monthly income, expenses, and net cash flow</title>{[1,.5,0,-.5,-1].map(ratio=>{const tickY=y(chartMax*ratio);return <g key={ratio}><line x1={axisLeft} y1={tickY} x2={axisRight} y2={tickY} className={ratio===0?'zero':''}/><text x="4" y={tickY+5}>{moneyTick(chartMax*ratio)}</text></g>})}{income.map((value,index)=>{const center=pointLeft+index*step,incomeY=y(value),expenseY=y(-expenses[index]);return <g key={`${labels[index]}-${index}`}><rect className="inc" x={center-barWidth-2} y={incomeY} width={barWidth} height={Math.max(0,zero-incomeY)} rx="4"><title>{labels[index]} income: {format(value)}</title></rect><rect className="out" x={center+2} y={zero} width={barWidth} height={Math.max(0,expenseY-zero)} rx="4"><title>{labels[index]} expenses: {format(expenses[index])}</title></rect><text x={center} y="263" textAnchor="middle">{labels[index]}</text></g>})}<path className="netline" d={net.map((value,index)=>`${index?'L':'M'}${pointLeft+index*step} ${y(value)}`).join(' ')}/>{net.map((value,index)=><circle key={`${labels[index]}-net`} cx={pointLeft+index*step} cy={y(value)} r="5"><title>{labels[index]} net: {format(value)}</title></circle>)}</svg>}
function BudgetChart({labels,planned,actual}:{labels:string[];planned:number[];actual:number[]}){const maximum=Math.max(1,...planned,...actual),chartMax=Math.ceil(maximum/(10**Math.floor(Math.log10(maximum))))*(10**Math.floor(Math.log10(maximum))),left=64,right=936,top=22,bottom=226,step=(right-left)/Math.max(1,labels.length),barWidth=Math.min(34,Math.max(16,step*.28)),y=(value:number)=>bottom-(value/chartMax)*(bottom-top),tick=(value:number)=>value>=1000?`₱${Number((value/1000).toFixed(1))}K`:`₱${value}`;return <svg className="budget-chart" viewBox="0 0 980 280" role="img" aria-label="Monthly budget versus actual spending by subcategory"><title>Monthly budget versus actual spending</title>{[1,.75,.5,.25,0].map(ratio=>{const yy=y(chartMax*ratio);return <g key={ratio}><line x1="54" y1={yy} x2="954" y2={yy}/><text x="4" y={yy+5}>{tick(chartMax*ratio)}</text></g>})}{labels.length?labels.map((label,index)=>{const center=left+step*(index+.5),plannedY=y(planned[index]),actualY=y(actual[index]);return <g key={`${label}-${index}`}><rect className="budget-bar" x={center-barWidth-2} y={plannedY} width={barWidth} height={bottom-plannedY} rx="4"><title>{label} budget: {format(planned[index])}</title></rect><rect className="out" x={center+2} y={actualY} width={barWidth} height={bottom-actualY} rx="4"><title>{label} actual: {format(actual[index])}</title></rect><text x={center} y="263" textAnchor="middle">{label.length>11?`${label.slice(0,10)}…`:label}</text></g>}):<text className="chart-empty" x="490" y="135" textAnchor="middle">No budget data yet</text>}</svg>}
function Mini({tone,icon,title,value,count,labels,onClick}:{tone:string;icon:string;title:string;value:string;count:string;labels:string[];onClick:()=>void}){return <article><div><i className={tone}>{icon}</i><b>{title}</b></div><section><span><strong>{value}</strong><small>{labels[0]}</small></span><span><strong>{count}</strong><small>{labels[1]}</small></span></section><button onClick={onClick}>View details</button></article>}
