import { useMemo, useState } from 'react'
import { ArrowDown, ArrowUp, Check, CircleDollarSign, CreditCard, Download, Info, PiggyBank, Receipt, TrendingUp, Wallet } from 'lucide-react'
import { useFirestoreState } from './hooks/useFirestoreState'
import { useWalletSnapshot } from './hooks/useWalletSnapshot'
import type { CategoryBudget, Debt, Installment, Receivable } from './domain/planningEngine'
import { receivableOutstanding } from './domain/planningEngine'
import { connectBudgetsToTransactions } from './utils/budgetSpending'
import { filterIncludedCardTransactions } from './utils/netBalanceFilters'

type Props={onNotice:(text:string)=>void}
type WalletData={accounts?:Array<{balance:number}>;cards?:Array<{id:number|string;active?:boolean;includeInNetBalance?:boolean}>;accountTransactions?:Array<{date:string;type:string;category?:string;amount:number}>;transactions?:Array<{cardId:number|string;postedDate:string;transactionDate?:string;type:string;category?:string;amount:number;status:string}>;payments?:Array<{cardId?:number|string;amount:number;date?:string;paidAt?:string;status:string}>}
type ExpenseCategoryGroup={name:string;total:number;subcategories:Array<{name:string;amount:number}>}
const peso=(n:number)=>`${n<0?'−':''}₱${Math.abs(n).toLocaleString('en-PH',{maximumFractionDigits:2})}`
const monthKey=()=>new Date().toISOString().slice(0,7)
type PnlRange="previous-month"|"this-month"|"last-3-months"|"last-6-months"|"last-1-year"|"custom"
const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
const monthStart=(date:Date)=>new Date(date.getFullYear(),date.getMonth(),1,12)
const monthEnd=(date:Date)=>new Date(date.getFullYear(),date.getMonth()+1,0,12)
function getRangeDates(range:PnlRange,customFrom:string,customTo:string){
  const today=new Date(),currentStart=monthStart(today),currentEnd=monthEnd(today)
  if(range==="previous-month"){const previous=new Date(today.getFullYear(),today.getMonth()-1,1,12);return{from:iso(monthStart(previous)),to:iso(monthEnd(previous)),label:previous.toLocaleDateString('en-US',{month:'long',year:'numeric'})}}
  if(range==="this-month")return{from:iso(currentStart),to:iso(currentEnd),label:today.toLocaleDateString('en-US',{month:'long',year:'numeric'})}
  if(range==="last-3-months"){const start=new Date(today.getFullYear(),today.getMonth()-2,1,12);return{from:iso(start),to:iso(currentEnd),label:"Last 3 months"}}
  if(range==="last-6-months"){const start=new Date(today.getFullYear(),today.getMonth()-5,1,12);return{from:iso(start),to:iso(currentEnd),label:"Last 6 months"}}
  if(range==="last-1-year"){const start=new Date(today.getFullYear(),today.getMonth()-11,1,12);return{from:iso(start),to:iso(currentEnd),label:"Last 1 year"}}
  const fallbackFrom=iso(currentStart),fallbackTo=iso(currentEnd),from=customFrom||fallbackFrom,to=customTo||fallbackTo
  return{from:from<=to?from:to,to:from<=to?to:from,label:`${from<=to?from:to} to ${from<=to?to:from}`}
}
const inDateRange=(value:string|undefined,from:string,to:string)=>Boolean(value&&value>=from&&value<=to)
const subcategoryName=(category='Uncategorized')=>category.includes('/')?category.split('/').map(part=>part.trim()).filter(Boolean).at(-1)||category:category
const categoryParts=(category='Uncategorized')=>{const parts=category.split('/').map(part=>part.trim()).filter(Boolean);return{parent:parts[0]||'Uncategorized',subcategory:parts.length>1?parts.at(-1)??null:null}}
const isCreditCardCategory=(category='')=>categoryParts(category).parent.toLowerCase()==='credit card'
const groupedExpenseRows=(items:Array<{category:string;amount:number}>):ExpenseCategoryGroup[]=>{
  const groups=new Map<string,{total:number;subcategories:Map<string,number>}>()
  items.forEach(item=>{
    const {parent,subcategory}=categoryParts(item.category||'Uncategorized'),group=groups.get(parent)??{total:0,subcategories:new Map<string,number>()}
    group.total+=item.amount
    if(subcategory)group.subcategories.set(subcategory,(group.subcategories.get(subcategory)||0)+item.amount)
    groups.set(parent,group)
  })
  return [...groups.entries()].map(([name,group])=>({name,total:group.total,subcategories:[...group.subcategories.entries()].map(([subName,amount])=>({name:subName,amount})).sort((a,b)=>b.amount-a.amount)})).sort((a,b)=>b.total-a.total)
}

export default function ReportsAnalytics({onNotice}:Props){
  const [view,setView]=useState<'Weekly'|'Monthly'|'ProfitLoss'>('Weekly')
  const [pnlRange,setPnlRange]=useState<PnlRange>('this-month')
  const [pnlCustomFrom,setPnlCustomFrom]=useState('')
  const [pnlCustomTo,setPnlCustomTo]=useState('')
  const [wallet]=useWalletSnapshot<WalletData>({})
  const [budgets]=useFirestoreState<CategoryBudget[]>('budgets',[])
  const [goals]=useFirestoreState<string[][]>('savingsGoals',[])
  const [debts]=useFirestoreState<Debt[]>('debts',[])
  const [receivables]=useFirestoreState<Receivable[]>('receivables',[])
  const [installments]=useFirestoreState<Installment[]>('installments',[])
  const pnlRangeDates=useMemo(()=>getRangeDates(pnlRange,pnlCustomFrom,pnlCustomTo),[pnlRange,pnlCustomFrom,pnlCustomTo])
  const data=useMemo(()=>{
    const includedCardTransactions=filterIncludedCardTransactions(wallet.transactions??[],wallet.cards??[])
    const key=monthKey(),accountMonth=(wallet.accountTransactions??[]).filter(item=>item.date.startsWith(key)),cardMonth=includedCardTransactions.filter(item=>(item.transactionDate||item.postedDate).startsWith(key)&&item.status?.toLowerCase()==='posted')
    const income=accountMonth.filter(item=>item.type==='Income').reduce((sum,item)=>sum+Number(item.amount||0),0)
    const expenses=accountMonth.filter(item=>item.type==='Expense').reduce((sum,item)=>sum+Number(item.amount||0),0)+cardMonth.filter(item=>['purchase','installment','fee','interest'].includes(item.type.toLowerCase())).reduce((sum,item)=>sum+Number(item.amount||0),0)
    const includedCardIds=new Set((wallet.cards??[]).filter(card=>card.active!==false&&card.includeInNetBalance!==false).map(card=>String(card.id)))
    const cards=(wallet.payments??[]).filter(item=>(item.cardId===undefined||includedCardIds.has(String(item.cardId)))&&(item.date||item.paidAt||'').startsWith(key)&&item.status!=='Cancelled').reduce((sum,item)=>sum+Number(item.amount||0),0)
    const savings=goals.reduce((sum,goal)=>sum+(Number(String(goal[5]||'').replace(/[^0-9.-]/g,''))||0),0)
    const connectedBudgets=connectBudgetsToTransactions(budgets,{accountTransactions:wallet.accountTransactions,transactions:includedCardTransactions,cards:wallet.cards}).filter(item=>!item.archived)
    const budget=connectedBudgets.reduce((sum,item)=>sum+item.allocated,0)
    const categories=connectedBudgets.slice(0,6).map((item,index)=>[item.subcategory||item.name,item.actual,['#238653','#ec6b54','#4f72b5','#e69b1f','#8b62bd','#0f766e'][index%6]] as [string,number,string])
    const months=Array.from({length:6},(_,index)=>{
      const date=new Date(new Date().getFullYear(),new Date().getMonth()-5+index,1),month=date.toLocaleDateString('en-US',{month:'short'}),mk=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`
      return{month,income:(wallet.accountTransactions??[]).filter(item=>item.date.startsWith(mk)&&item.type==='Income').reduce((sum,item)=>sum+Number(item.amount||0),0),expenses:(wallet.accountTransactions??[]).filter(item=>item.date.startsWith(mk)&&item.type==='Expense').reduce((sum,item)=>sum+Number(item.amount||0),0)+includedCardTransactions.filter(item=>(item.transactionDate||item.postedDate).startsWith(mk)&&['purchase','installment','fee','interest'].includes(item.type.toLowerCase())).reduce((sum,item)=>sum+Number(item.amount||0),0),savings}
    })
    const accountPnl=(wallet.accountTransactions??[]).filter(item=>inDateRange(item.date,pnlRangeDates.from,pnlRangeDates.to))
    const cardPnl=includedCardTransactions.filter(item=>inDateRange(item.transactionDate||item.postedDate,pnlRangeDates.from,pnlRangeDates.to)&&item.status?.toLowerCase()==='posted')
    const pnlIncome=accountPnl.filter(item=>item.type==='Income').reduce((sum,item)=>sum+Number(item.amount||0),0)
    const pnlExpenseItems=[...accountPnl.filter(item=>item.type==='Expense').map(item=>({category:item.category||'Uncategorized',amount:Number(item.amount||0)})),...cardPnl.filter(item=>['purchase','installment','fee','interest'].includes(item.type.toLowerCase())).map(item=>({category:item.category||'Uncategorized',amount:Number(item.amount||0)}))].filter(item=>!isCreditCardCategory(item.category))
    const pnlExpenses=pnlExpenseItems.reduce((sum,item)=>sum+item.amount,0)
    const operatingExpenseItems=pnlExpenseItems
    const operatingExpensesByCategory=groupedExpenseRows(operatingExpenseItems)
    const incomeBySubcategory=accountPnl.filter(item=>item.type==='Income').map(item=>({category:subcategoryName(item.category||'Uncategorized'),amount:Number(item.amount||0)}))
      .reduce((rows,item)=>{rows[item.category]=(rows[item.category]||0)+item.amount;return rows},{} as Record<string,number>)
    return{income,expenses,cards,savings,budget,categories,months,operatingExpensesByCategory,incomeBySubcategory,pnlIncome,pnlExpenses}
  },[budgets,goals,wallet,pnlRangeDates.from,pnlRangeDates.to])
  const weekly={income:data.income,expenses:data.expenses,bills:0,cards:data.cards,savings:data.savings,starting:(wallet.accounts??[]).reduce((sum,item)=>sum+Number(item.balance||0),0)}
  const monthly={income:data.income,expenses:data.expenses,cards:data.cards,savings:data.savings,budget:data.budget}
  const weeklyNet=weekly.income-weekly.expenses-weekly.cards,weeklyEnding=weekly.starting+weeklyNet-weekly.savings,monthlyNet=monthly.income-monthly.expenses-monthly.cards,savingsRate=monthly.income?monthly.savings/monthly.income*100:0,variance=monthly.expenses-monthly.budget
  const pnl={revenue:data.pnlIncome,expenses:data.pnlExpenses,netProfit:data.pnlIncome-data.pnlExpenses,margin:data.pnlIncome?(data.pnlIncome-data.pnlExpenses)/data.pnlIncome*100:0,incomeRows:Object.entries(data.incomeBySubcategory).sort((a,b)=>b[1]-a[1]),expenseRows:data.operatingExpensesByCategory}
  return <section className="feature-page reports-analytics rounded-report-page"><div className="fp-head"><div><h2>Reports & Analytics</h2><p>Understand cash flow, spending patterns, and savings performance.</p></div><button className="outline report-export" onClick={()=>onNotice(`${view} report exported`)}><Download/>Export report</button></div>
    <div className="report-toolbar"><div role="tablist"><button role="tab" aria-selected={view==='Weekly'} className={view==='Weekly'?'active':''} onClick={()=>setView('Weekly')}>Weekly report</button><button role="tab" aria-selected={view==='Monthly'} className={view==='Monthly'?'active':''} onClick={()=>setView('Monthly')}>Monthly report</button><button role="tab" aria-selected={view==='ProfitLoss'} className={view==='ProfitLoss'?'active':''} onClick={()=>setView('ProfitLoss')}>Profit & Loss</button></div><select aria-label="Report period" defaultValue={view==='Weekly'?'Current week':'Current month'} key={view}>{view==='Weekly'?<><option>Current week</option><option>Previous week</option></>:<><option>Current month</option><option>Previous month</option></>}</select></div>
    {view==='Weekly'?<><div className="report-metrics weekly-report-metrics"><Metric label="Income received" value={weekly.income} icon={CircleDollarSign} tone="positive"/><Metric label="Expenses paid" value={weekly.expenses} icon={Receipt}/><Metric label="Credit card payments" value={weekly.cards} icon={CreditCard}/><Metric label="Net cash flow" value={weeklyNet} icon={TrendingUp} tone={weeklyNet>=0?'positive':'negative'}/></div>
      <div className="weekly-report-layout"><article className="surface weekly-flow-report"><div className="surface-title"><div><b>Weekly cash-flow statement</b><small>Current saved records</small></div><span className={weeklyEnding>=0?'positive':'negative'}><Check/>{weeklyEnding>=0?'Ending positive':'Ending negative'}</span></div><div className="statement-start"><span>Beginning balance</span><b>{peso(weekly.starting)}</b></div><div className="statement-lines"><div className="in"><span><ArrowUp/>Income received</span><b>+{peso(weekly.income)}</b></div><div><span><ArrowDown/>Bills paid</span><b>−{peso(weekly.bills)}</b></div><div><span><ArrowDown/>Other expenses paid</span><b>−{peso(Math.max(0,weekly.expenses-weekly.bills))}</b></div><div><span><CreditCard/>Credit card payments</span><b>−{peso(weekly.cards)}</b></div><div><span><PiggyBank/>Savings contributions</span><b>−{peso(weekly.savings)}</b></div></div><div className="statement-total"><span>Ending balance</span><b>{peso(weeklyEnding)}</b></div></article>
        <aside className="surface report-formulas"><div className="formula-block"><span><TrendingUp/></span><div><small>Net cash flow</small><b>{peso(weeklyNet)}</b><p>Total income − total expenses − credit card payments</p></div></div><div className="formula-equation"><span>{peso(weekly.income)}</span><i>−</i><span>{peso(weekly.expenses)}</span><i>−</i><span>{peso(weekly.cards)}</span><i>=</i><b>{peso(weeklyNet)}</b></div><div className="transfer-rule"><Info/><span><b>Transfers excluded</b><small>Transfers between personal accounts are not counted as income or expenses.</small></span></div></aside>
      </div></>:view==='Monthly'?<><div className="report-metrics monthly-report-metrics"><Metric label="Total income" value={monthly.income} icon={CircleDollarSign} tone="positive"/><Metric label="Total expenses" value={monthly.expenses} icon={Receipt}/><Metric label="Savings rate" value={`${savingsRate.toFixed(1)}%`} icon={PiggyBank} tone="positive"/><Metric label="Credit card payments" value={monthly.cards} icon={CreditCard}/><Metric label="Budget variance" value={`${variance>0?'+':''}${peso(variance)}`} icon={Wallet} tone={variance>0?'negative':'positive'}/></div>
      <div className="monthly-report-grid"><article className="surface category-report"><div className="surface-title"><div><b>Spending by category</b><small>{peso(monthly.expenses)} total expenses</small></div></div><div className="category-bars">{data.categories.length?data.categories.map(([name,value,color])=><div key={String(name)}><span><b>{name}</b><small>{peso(Number(value))} · {monthly.expenses?(Number(value)/monthly.expenses*100).toFixed(1):0}%</small></span><i><em style={{width:`${monthly.expenses?Number(value)/monthly.expenses*100:0}%`,background:String(color)}}/></i></div>):<p className="empty-card">No category spending recorded.</p>}</div></article><article className="surface largest-expenses"><div className="surface-title"><b>Largest expenses</b></div>{data.categories.length?data.categories.slice(0,4).map(([name,,],i)=><div key={String(name)}><span>{i+1}</span><p><b>{name}</b><small>Budget category</small></p><strong>{peso(Number(data.categories[i][1]))}</strong></div>):<p className="empty-card">No expenses yet.</p>}</article>
        <article className="surface month-comparison"><div className="surface-title"><div><b>Month-over-month comparison</b><small>Income, expenses, and savings</small></div></div><div className="comparison-chart">{data.months.map(m=><div key={m.month}><div className="comparison-bars"><i className="income" style={{height:`${Math.min(130,m.income/Math.max(1,monthly.income,monthly.expenses)*130)}px`}}/><i className="expenses" style={{height:`${Math.min(130,m.expenses/Math.max(1,monthly.income,monthly.expenses)*130)}px`}}/><i className="savings" style={{height:`${Math.min(130,m.savings/Math.max(1,monthly.income,monthly.expenses)*130)}px`}}/></div><b>{m.month}</b></div>)}</div><div className="comparison-legend"><span><i className="income"/>Income</span><span><i className="expenses"/>Expenses</span><span><i className="savings"/>Savings</span></div></article><article className="surface savings-rate-panel"><span><PiggyBank/></span><small>Savings rate</small><strong>{savingsRate.toFixed(1)}%</strong><p>Savings contributions ÷ total income × 100</p><div><b>{peso(monthly.savings)}</b><i>÷</i><b>{peso(monthly.income)}</b><i>× 100</i></div><em className={savingsRate>0?'positive':''}><ArrowUp/>{savingsRate>0?'Savings recorded':'No savings yet'}</em></article>
      </div><div className="transfer-exclusion"><Info/><p><b>Personal transfers are excluded from reporting.</b> Moving money between your own accounts does not increase income or expenses.</p><span>Auto-calculated</span></div></>:<><div className="pnl-period-panel surface"><div><b>Profit & Loss date range</b><small>{pnlRangeDates.from} to {pnlRangeDates.to}</small></div><select aria-label="Profit and Loss date range" value={pnlRange} onChange={event=>setPnlRange(event.target.value as PnlRange)}><option value="previous-month">Previous month</option><option value="this-month">This month</option><option value="last-3-months">Last 3 months</option><option value="last-6-months">Last 6 months</option><option value="last-1-year">Last 1 year</option><option value="custom">Custom date range</option></select>{pnlRange==='custom'&&<div className="pnl-custom-dates"><label>From<input type="date" value={pnlCustomFrom} onChange={event=>setPnlCustomFrom(event.target.value)}/></label><label>To<input type="date" value={pnlCustomTo} onChange={event=>setPnlCustomTo(event.target.value)}/></label></div>}</div><div className="report-metrics pnl-report-metrics"><Metric label="Total revenue" value={pnl.revenue} icon={CircleDollarSign} tone="positive"/><Metric label="Operating expenses" value={pnl.expenses} icon={Receipt}/><Metric label="Net profit / loss" value={pnl.netProfit} icon={TrendingUp} tone={pnl.netProfit>=0?'positive':'negative'}/><Metric label="Profit margin" value={`${pnl.margin.toFixed(1)}%`} icon={Wallet} tone={pnl.margin>=0?'positive':'negative'}/></div>
      <div className="pnl-report-grid">
        <article className="surface pnl-statement"><div className="surface-title"><div><b>Profit & Loss Statement</b><small>{pnlRangeDates.label} · Posted income and expenses</small></div></div><div className="pnl-lines"><div className="pnl-group revenue-group"><small>Income by sub-category</small>{pnl.incomeRows.length?pnl.incomeRows.map(([name,amount])=><div className="pnl-line" key={name}><span>{name}</span><b className="positive">+{peso(amount)}</b></div>):<p className="empty-card">No income recorded for this period.</p>}</div><div className="pnl-line total"><span>Total revenue</span><b className="positive">{peso(pnl.revenue)}</b></div><div className="pnl-group"><small>Operating expenses</small>{pnl.expenseRows.length?<ExpenseCategoryLines rows={pnl.expenseRows}/>:<p className="empty-card">No expenses recorded for this period.</p>}</div><div className="pnl-line subtotal"><span>Total operating expenses</span><b>−{peso(pnl.expenses)}</b></div><div className={`pnl-line net ${pnl.netProfit>=0?'positive-row':'negative-row'}`}><span>{pnl.netProfit>=0?'Net profit':'Net loss'}</span><b>{peso(pnl.netProfit)}</b></div></div></article>
        <aside className="surface pnl-notes"><div className="formula-block"><span><Info/></span><div><small>How this is calculated</small><b>{peso(pnl.revenue)} − {peso(pnl.expenses)} = {peso(pnl.netProfit)}</b><p>Credit card purchases count as expenses when posted. Credit card payments and personal transfers are excluded from Profit & Loss to avoid double counting.</p></div></div><div className="transfer-rule"><CreditCard/><span><b>Card payments excluded</b><small>Purchases affect expenses; payments only move money between accounts/liabilities.</small></span></div><div className="transfer-rule"><Wallet/><span><b>Personal-use report</b><small>This is a financial performance view, not a tax filing report.</small></span></div></aside>
      </div></>}
    <article className="surface advanced-report-summary"><div className="surface-title"><b>Advanced planning report</b><button className="link" onClick={()=>onNotice('Advanced planning report exported')}>Export CSV / Excel / PDF</button></div><div><span><small>Budget remaining</small><b className="positive">{peso(Math.max(0,monthly.budget-monthly.expenses))}</b></span><span><small>Debt outstanding</small><b>{peso(debts.reduce((sum,item)=>sum+Number(item.balance||0),0))}</b></span><span><small>Receivables outstanding</small><b className="positive">{peso(receivables.reduce((sum,item)=>sum+receivableOutstanding(item),0))}</b></span><span><small>Net cash flow</small><b className={monthlyNet>=0?'positive':'negative'}>{peso(monthlyNet)}</b></span><span><small>Installments remaining</small><b>{peso(installments.reduce((sum,item)=>sum+Number(item.remainingPayable||0),0))}</b></span></div><p><Info/>Principal borrowing, lending, collections, transfers, and credit-card payments are excluded from ordinary income and expenses.</p></article>
  </section>
}
function Metric({label,value,icon:Icon,tone=''}:{label:string;value:number|string;icon:typeof Receipt;tone?:string}){return <article><span className={tone}><Icon/></span><div><small>{label}</small><b className={tone}>{typeof value==='number'?peso(value):value}</b></div></article>}
function ExpenseCategoryLines({rows}:{rows:ExpenseCategoryGroup[]}){
  return <>{rows.map(row=><div className="pnl-category-tree" key={row.name}><div className="pnl-line category-parent"><span>{row.name}</span><b>−{peso(row.total)}</b></div>{row.subcategories.map(subcategory=><div className="pnl-line category-child" key={`${row.name}-${subcategory.name}`}><span>{subcategory.name}</span><b>−{peso(subcategory.amount)}</b></div>)}</div>)}</>
}
